import { UserAgentProvider } from "@/src/user-agent-provider";
import { getUserAgent } from "@/src/get-user-agent/app";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <UserAgentProvider userAgent={getUserAgent()}>
          {children}
        </UserAgentProvider>
      </body>
    </html>
  );
}
